name: flutter_diprovet_cliente
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.5.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.1
  lottie: ^3.1.2
  path_provider: ^2.1.3
  provider: ^6.0.3
  screenshot: ^3.0.0
  very_good_analysis: ^6.0.0
  intl: ^0.19.0
  share_plus: ^7.2.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/lottie/
    - assets/lottie/home/